fixup! drivers: leds: Remove duplicate LEDS_KTD2692 entries
config LEDS_KTD2692 should depend on LEDS_CLASS instead of
LEDS_CLASS_FLASH, just like the other led drivers, not using that causes
the following compilation errors on the Galaxy S20 FE (codename: r8q)

../techpack/sec-camera/drivers/cam_sensor_module/cam_flash/cam_flash_core.c:585:29:
error: implicit declaration of function
      'sec_hw_rev' [-Werror,-Wimplicit-function-declaration]
  585 |                         unsigned int board_rev = sec_hw_rev();
      |                                                  ^
../techpack/sec-camera/drivers/cam_sensor_module/cam_flash/cam_flash_core.c:593:5:
error: implicit declaration of function
      'ktd2692_led_mode_ctrl' [-Werror,-Wimplicit-function-declaration]
  593 |                                 ktd2692_led_mode_ctrl(KTD2692_DISABLES_TORCH_FLASH_MODE, 0);
      |                                 ^
../techpack/sec-camera/drivers/cam_sensor_module/cam_flash/cam_flash_core.c:593:5:
note: did you mean 'rt8547_led_mode_ctrl'?
../include/linux/leds-rt8547.h:165:16: note: 'rt8547_led_mode_ctrl'
declared here
  165 | extern int64_t rt8547_led_mode_ctrl(int state, int value);
      |                ^
  CC      net/ipv6/tunnel6.o
../techpack/sec-camera/drivers/cam_sensor_module/cam_flash/cam_flash_core.c:593:27:
error: use of undeclared identifier
      'KTD2692_DISABLES_TORCH_FLASH_MODE'; did you mean 'RT8547_DISABLES_TORCH_FLASH_MODE'?
  593 |                                 ktd2692_led_mode_ctrl(KTD2692_DISABLES_TORCH_FLASH_MODE, 0);
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       RT8547_DISABLES_TORCH_FLASH_MODE
../include/linux/leds-rt8547.h:143:2: note:
'RT8547_DISABLES_TORCH_FLASH_MODE' declared here
  143 |         RT8547_DISABLES_TORCH_FLASH_MODE = 0x0,
      |         ^

Change-Id: I15d7c81ef5f2b419c78b8aad2d3c15840d34c3cc